
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("86e61282-a810-475f-91ba-431eccad3831")>

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class CarsDBEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new CarsDBEntities object using the connection string found in the 'CarsDBEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=CarsDBEntities", "CarsDBEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new CarsDBEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "CarsDBEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new CarsDBEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "CarsDBEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property CarScheduling() As ObjectSet(Of CarScheduling)
        Get
            If (_CarScheduling Is Nothing) Then
                _CarScheduling = MyBase.CreateObjectSet(Of CarScheduling)("CarScheduling")
            End If
            Return _CarScheduling
        End Get
    End Property

    Private _CarScheduling As ObjectSet(Of CarScheduling)

    #End Region
    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the CarScheduling EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToCarScheduling(ByVal carScheduling As CarScheduling)
        MyBase.AddObject("CarScheduling", carScheduling)
    End Sub

    #End Region
End Class

#End Region
#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="CarsDBModel", Name:="CarScheduling")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class CarScheduling
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new CarScheduling object.
    ''' </summary>
    ''' <param name="id">Initial value of the ID property.</param>
    ''' <param name="allDay">Initial value of the AllDay property.</param>
    Public Shared Function CreateCarScheduling(id As Global.System.Int32, allDay As Global.System.Boolean) As CarScheduling
        Dim carScheduling as CarScheduling = New CarScheduling
        carScheduling.ID = id
        carScheduling.AllDay = allDay
        Return carScheduling
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ID() As Global.System.Int32
        Get
            Return _ID
        End Get
        Set
            If (_ID <> Value) Then
                OnIDChanging(value)
                ReportPropertyChanging("ID")
                _ID = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("ID")
                OnIDChanged()
            End If
        End Set
    End Property

    Private _ID As Global.System.Int32
    Private Partial Sub OnIDChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CarId() As Nullable(Of Global.System.Int32)
        Get
            Return _CarId
        End Get
        Set
            OnCarIdChanging(value)
            ReportPropertyChanging("CarId")
            _CarId = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("CarId")
            OnCarIdChanged()
        End Set
    End Property

    Private _CarId As Nullable(Of Global.System.Int32)
    Private Partial Sub OnCarIdChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnCarIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property UserId() As Nullable(Of Global.System.Int32)
        Get
            Return _UserId
        End Get
        Set
            OnUserIdChanging(value)
            ReportPropertyChanging("UserId")
            _UserId = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("UserId")
            OnUserIdChanged()
        End Set
    End Property

    Private _UserId As Nullable(Of Global.System.Int32)
    Private Partial Sub OnUserIdChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnUserIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Status() As Nullable(Of Global.System.Int32)
        Get
            Return _Status
        End Get
        Set
            OnStatusChanging(value)
            ReportPropertyChanging("Status")
            _Status = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Status")
            OnStatusChanged()
        End Set
    End Property

    Private _Status As Nullable(Of Global.System.Int32)
    Private Partial Sub OnStatusChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnStatusChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Subject() As Global.System.String
        Get
            Return _Subject
        End Get
        Set
            OnSubjectChanging(value)
            ReportPropertyChanging("Subject")
            _Subject = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Subject")
            OnSubjectChanged()
        End Set
    End Property

    Private _Subject As Global.System.String
    Private Partial Sub OnSubjectChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnSubjectChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Description() As Global.System.String
        Get
            Return _Description
        End Get
        Set
            OnDescriptionChanging(value)
            ReportPropertyChanging("Description")
            _Description = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Description")
            OnDescriptionChanged()
        End Set
    End Property

    Private _Description As Global.System.String
    Private Partial Sub OnDescriptionChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDescriptionChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Label() As Nullable(Of Global.System.Int32)
        Get
            Return _Label
        End Get
        Set
            OnLabelChanging(value)
            ReportPropertyChanging("Label")
            _Label = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Label")
            OnLabelChanged()
        End Set
    End Property

    Private _Label As Nullable(Of Global.System.Int32)
    Private Partial Sub OnLabelChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnLabelChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property StartTime() As Nullable(Of Global.System.DateTime)
        Get
            Return _StartTime
        End Get
        Set
            OnStartTimeChanging(value)
            ReportPropertyChanging("StartTime")
            _StartTime = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("StartTime")
            OnStartTimeChanged()
        End Set
    End Property

    Private _StartTime As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnStartTimeChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnStartTimeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property EndTime() As Nullable(Of Global.System.DateTime)
        Get
            Return _EndTime
        End Get
        Set
            OnEndTimeChanging(value)
            ReportPropertyChanging("EndTime")
            _EndTime = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("EndTime")
            OnEndTimeChanged()
        End Set
    End Property

    Private _EndTime As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnEndTimeChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnEndTimeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Location() As Global.System.String
        Get
            Return _Location
        End Get
        Set
            OnLocationChanging(value)
            ReportPropertyChanging("Location")
            _Location = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Location")
            OnLocationChanged()
        End Set
    End Property

    Private _Location As Global.System.String
    Private Partial Sub OnLocationChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnLocationChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property AllDay() As Global.System.Boolean
        Get
            Return _AllDay
        End Get
        Set
            OnAllDayChanging(value)
            ReportPropertyChanging("AllDay")
            _AllDay = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("AllDay")
            OnAllDayChanged()
        End Set
    End Property

    Private _AllDay As Global.System.Boolean
    Private Partial Sub OnAllDayChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnAllDayChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property EventType() As Nullable(Of Global.System.Int32)
        Get
            Return _EventType
        End Get
        Set
            OnEventTypeChanging(value)
            ReportPropertyChanging("EventType")
            _EventType = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("EventType")
            OnEventTypeChanged()
        End Set
    End Property

    Private _EventType As Nullable(Of Global.System.Int32)
    Private Partial Sub OnEventTypeChanging(value As Nullable(Of Global.System.Int32))
    End Sub

    Private Partial Sub OnEventTypeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property RecurrenceInfo() As Global.System.String
        Get
            Return _RecurrenceInfo
        End Get
        Set
            OnRecurrenceInfoChanging(value)
            ReportPropertyChanging("RecurrenceInfo")
            _RecurrenceInfo = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("RecurrenceInfo")
            OnRecurrenceInfoChanged()
        End Set
    End Property

    Private _RecurrenceInfo As Global.System.String
    Private Partial Sub OnRecurrenceInfoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnRecurrenceInfoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ReminderInfo() As Global.System.String
        Get
            Return _ReminderInfo
        End Get
        Set
            OnReminderInfoChanging(value)
            ReportPropertyChanging("ReminderInfo")
            _ReminderInfo = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("ReminderInfo")
            OnReminderInfoChanged()
        End Set
    End Property

    Private _ReminderInfo As Global.System.String
    Private Partial Sub OnReminderInfoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnReminderInfoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Price() As Nullable(Of Global.System.Decimal)
        Get
            Return _Price
        End Get
        Set
            OnPriceChanging(value)
            ReportPropertyChanging("Price")
            _Price = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Price")
            OnPriceChanged()
        End Set
    End Property

    Private _Price As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnPriceChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnPriceChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ContactInfo() As Global.System.String
        Get
            Return _ContactInfo
        End Get
        Set
            OnContactInfoChanging(value)
            ReportPropertyChanging("ContactInfo")
            _ContactInfo = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("ContactInfo")
            OnContactInfoChanged()
        End Set
    End Property

    Private _ContactInfo As Global.System.String
    Private Partial Sub OnContactInfoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnContactInfoChanged()
    End Sub

    #End Region
End Class

#End Region

